'use strict';

//user
export const USER_NAME_UPDATED = 'USER_NAME_UPDATED';
export const USER_EMAIL_UPDATED = 'USER_EMAIL_UPDATED';
export const USER_PASSWORD_UPDATED = 'USER_PASSWORD_UPDATED';
export const USER_NICKNAME_UPDATED = 'USER_NICKNAME_UPDATED';
export const USER_MOBILE_NUMBER_UPDATED = 'USER_MOBILE_NUMBER_UPDATED';
export const USER_ADDRESS_UPDATED = 'USER_ADDRESS_UPDATED';
export const USER_STATUS_VERIFIED = 'USER_STATUS_VERIFIED';
export const USER_AUTHORIZED = 'USER_AUTHORIZED';

// alert popup
export const ALERT_POPUP_SHOWN = 'ALERT_POPUP_SHOWN';
export const ALERT_POPUP_HIDDEN = 'ALERT_POPUP_HIDDEN';

// confirmation popup
export const CONFIRMATION_POPUP_SHOWN = 'CONFIRMATION_POPUP_SHOWN';
export const CONFIRMATION_POPUP_HIDDEN = 'CONFIRMATION_POPUP_HIDDEN';

// verify code
export const VERIFY_CODE_SHOWN = 'VERIFY_CODE_SHOWN';
export const VERIFY_CODE_HIDDEN = 'VERIFY_CODE_HIDDEN';